set titlestring=gvim
" guioptions {{{1
set guioptions=
set guioptions+=c
set guioptions+=e
set guioptions+=i
" no bell
set vb t_vb=

" guitablabel {{{1
"
nnoremap <M-n> :let t:mytabname = input(">")<cr>
set guitablabel=%{GuiTabLabel()}
function! GuiTabLabel()
  " this is defined in the main vim file for non-gui tabs
  if exists("t:mytabname") && len(t:mytabname) > 0
    return t:mytabname
  else
    return MyTabLabel(v:lnum)
  endif
endfunc

" guifont {{{1
set guifont=Inconsolata\ Medium\ 16
" set guifont=Noto\ Mono\ 13
" changing font size {{{1
nnoremap <c-up>   :let &guifont = substitute(&guifont, '\d\+', '\=eval(submatch(0)+1)', '')<cr>
nnoremap <c-down> :let &guifont = substitute(&guifont, '\d\+', '\=eval(submatch(0)-1)', '')<cr>
