export PATH=$PATH:~/bin
export PATH=$PATH:~/config/bin
export PATH=$PATH:~/.local/bin

export PATH=/usr/local/bin:$PATH
export PATH=/usr/local/sbin:$PATH
export PATH=/opt/local/bin:/opt/local/sbin:$PATH

# js paths
export PATH=~/.npm-global/bin:$PATH
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
#export VOLTA_HOME="$HOME/.volta"
#export PATH="$VOLTA_HOME/bin:$PATH"


# local env file
if [[ -f ~/.zshenv.local ]]; then
  . ~/.zshenv.local
fi

# local env file
if [[ -f ~/.zshenv.local ]]; then
  . ~/.zshenv.local
fi

# go paths
export GOPATH=~/go
export PATH=$GOPATH/bin:$GOROOT/bin:$PATH

# rust paths
export PATH=~/.cargo/bin:$PATH
export RUST_SRC_PATH=$( [[ -x $(which rustc) ]] && echo "$(rustc --print sysroot)/lib/rustlib/src/rust/src");
if [[ -f "$HOME/.cargo/env" ]]; then
  . "$HOME/.cargo/env"
fi

# vim paths
export EDITOR="nvim"

# java paths
if [[ -x /usr/libexec/java_home ]]; then
  #export JAVA_HOME=`/usr/libexec/java_home`
fi

# zig paths
export PATH=$PATH:~/bin/zig

# python paths
export PATH=$PATH:~/Library/Python/3.8/bin

# brew paths
export PATH=/opt/homebrew/bin:$PATH

# fzf setup
fzf_keybindings=~/config/nvim/plug/fzf/shell/key-bindings.zsh
fzf_completion=~/config/nvim/plug/fzf/shell/completion.zsh
bindkey '^R' fzf-history-widget
bindkey -M vicmd '^R' fzf-history-widget
[ -f $fzf_keybindings ] && source $fzf_keybindings
[ -f $fzf_completion ] && source $fzf_completion
export FZF_DEFAULT_COMMAND='
(git ls-tree -r --name-only HEAD ||
  find . -path "*/\.*" -prune -o -type f -print -o -type l -print |
  sed s/^..//) 2> /dev/null'
