[colors.bright]
black = "#4b565c"
blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

[colors.normal]
black = "#4b565c"
blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

[colors.primary]
background = "#272E33"
foreground = "#d3c6aa"

[font]
size = 12.0

[font.bold]
family = "FiraCode Nerd Font"

[font.italic]
family = "FiraCode Nerd Font"

[font.normal]
family = "FiraCode Nerd Font"

[general]
live_config_reload = true

[window]
decorations = "Full"
dynamic_padding = true
title = "terminal"
startup_mode = "Maximized"

[window.padding]
x = 0
y = 0

[bell]
command = { program = "notify-send", args = ["Claude Code", "Ready for input"] }
duration = 0
