snippet node "quick node config" !b
FROM node:0.10.38

RUN mkdir /src

RUN npm install -g forever

WORKDIR /src
ADD package.json /src/package.json
RUN npm install

EXPOSE 3000

CMD forever -w server.js
endsnippet
snippet nginx "Description" !b
FROM nginx
COPY nginx.conf /etc/nginx/nginx.conf
endsnippet
