#!/usr/bin/env sh

while true; do
  echo "[q]uit [e]edit [m]ove download [d]iff [r]ight flash [l]eft flash [f]lash both"
  read -n1 -r key
  case $key in
    e)
      cat MDErgo1-Blank.json | clip
      google-chrome-stable "http://input.club/configurator-ergodox" &
      ;;
    m)
      rm -rf ~/config/ergodox/{kll,log}
      mkdir -p /tmp/ergoautomator
      cd /tmp/ergoautomator
      mv ~/Downloads/MDErgo*.zip .
      unzip *.zip
      rm *.zip
      mv -f * ~/config/ergodox
      cd ~/config/ergodox
      rm -rf /tmp/ergoautomator
      echo "moved!"
      ;;
    r)
      echo "go into flash mode on the RIGHT and press any key to continue"
      read -n1 -r
      sudo dfu-util -D right_kiibohd.dfu.bin
      ;;
    l)
      echo "go into flash mode on the LEFT and press any key to continue"
      read -n1 -r
      sudo dfu-util -D left_kiibohd.dfu.bin
      ;;
    f)
      echo "go into flash mode on the LEFT and press any key to continue"
      read -n1 -r
      sudo dfu-util -D left_kiibohd.dfu.bin
      echo "go into flash mode on the RIGHT and press any key to continue"
      read -n1 -r
      sudo dfu-util -D right_kiibohd.dfu.bin
      ;;
    d)
      pwd
      git difftool ~/config/ergodox/*.json
      git st
      ;;
    q)
      break
      ;;
  esac
done;
